name: Build for Linux

on:
  - push
  - pull_request

jobs:
  build_wheels:
    name: Build wheel on Linux
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: actions/setup-python@v3
        name: Install Python 3.10
        with:
          python-version: "3.10"

      - uses: actions/setup-python@v3
        name: Install Python 3.9
        with:
          python-version: "3.9"

      - uses: actions/setup-python@v3
        name: Install Python 3.8
        with:
          python-version: "3.8"

      - uses: actions/setup-python@v3
        name: Install Python 3.7
        with:
          python-version: "3.7"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.4.0

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Test for Python 3.10
        run: |
          tox -e py310

      - name: Test for Python 3.9
        run: |
          tox -e py39

      - name: Test for Python 3.8
        run: |
          tox -e py38

      - name: Test for Python 3.7
        run: |
          tox -e py37

      - name: Build wheel
        if: contains(github.ref, 'tags/')
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v1
        if: contains(github.ref, 'tags/')
        with:
          name: wheels
          path: ./wheelhouse
